# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            supernoir
tagline:          'Crafting Interfaces with Code, Style and Love'
description:      'Show and Tell. Handcrafted by <a href="https://twitter.com/ckawohl" target="_blank">@ckawohl</a>.'
url:              http:supernoir.github.io
baseurl:          /

author:
  name:           'Conny Kawohl'
  url:            https://twitter.com/ckawohl

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/supernoir
